### PR TITLE
Add SoundCloud artist selector

### PR DESCRIPTION
**Pull request by nemchik**

### CODE REVIEW

**Comment by msfeldstein** [comment]
Confused here, since getArtist is overridden, when is this used?  I also don't think the username is usually the artist, i overrode gettitle and getartist so we can split track names on the hyphen

**Comment by nemchik** [comment]
It helps if i actually keep my local branches synced (had an issue, had to delete and recreate my whole git directory for all projects :( ). When I added that line my local copy of the file didn't have the overrides.
I only see some artists posting the artist name IN the song title. There are some issues with the overrides though now that I see them.
https://soundcloud.com/skinkofficial/showtek-satisfied-feat-vassy-blinders-remix this works fine.
https://soundcloud.com/iamharriscole/waves-kennysegal-ianewing-mrcarmack this has no artist with the overrides (but does with the selector).
https://soundcloud.com/eyeseverywhere/wuki-lip-pop-eyes-everywhere-remix-nest-hq-premiere this breaks off the end of the track name
https://soundcloud.com/thehbkgang/mad-feat-g-eazyprod-p-lo just for example, this one is posted with the actual title in quotes

As far as the username being the artist, the same would apply to youtube like this https://www.youtube.com/watch?v=OsqDpoaFVmU&list=TLNEMk6-_NTzQ
I agree with your thought that the username might not be the artist, but as far as soundcloud goes the username field is the most likely.

I'm not set in stone on any particular way of doing it, but the overrides currently seem to have some holes in them, and the selector idea is at least using what the site provides, rather than whatever format the users of the site happen to submit.

If you agree I'll update this PR and remove the overrides.

**Comment by msfeldstein** [comment]
Interesting it looks like the appropriate thing might be to try the hyphen
approach, and if that doesn't work, fall back to the name of the
publisher.  For the first example, Skink is not the artist.  If someone
posts a track with the title "Something Here - Something Else" that
probably means its a track by someone else, but if its just a string with
no hyphens its probably their track.

**Comment by msfeldstein** [comment]
And i think the eyeseverywhere track is just a really tough one, if we fix
that another tough one will break.

**Comment by nemchik** [comment]
For eyeseverywhere I think you would have to store `parts[0]` and then remove it from the array and join the remaining array with ` - `. That SHOULD work with others as well. But I generally don't like the lack of naming consistency on sound cloud anyway (still love the service though lol).

Seems like a lot of things to account for, I wonder if there is a decent code example out there somewhere for recognition (something like how iTunes or whatever can import a library with varying naming structure)

**Comment by msfeldstein** [comment]
Pushing the artistSelector as a fallback, but i had to simplify the selector, it didn't work for me as you had it.

**Comment by msfeldstein** [comment]
also fixed for when there's multiple hyphens, only splitting on the first one.

**Comment by nemchik** [comment]
I see the new commits to youtube but i think if you made changes to soundcloud after this merge they didn't commit.

**Comment by msfeldstein** [comment]
Oops forgot to push, https://github.com/msfeldstein/chrome-media-keys/commit/ba7064b1ad2b83f73a290a804150426ecce93e70

**Pull request merged**
