### PR TITLE
Update class targeting for Deezer controller

### LINKED ISSUE #97: Deezer controls not working anymore

### PR DESCRIPTION
**Pull request by RadValentin**
Fixes #97

### CODE REVIEW

**Comment by RadValentin** [comment]
BTW: When can we expect a new version to be pushed to the Chrome store? I'd really like to start using these fixes.

**Comment by msfeldstein** [comment]
I'll merge and do one tonight

**Comment by msfeldstein** [comment]
Just pushed 4.49, should be out in an hour.  `npm build` doesn't seem to do anything.

**Comment by valentin-radulescu-hs** [comment]
Awesome, ty!

`npm run build` should run [this task](https://github.com/msfeldstein/chrome-media-keys/blob/master/Gruntfile.coffee#L35). Is it not working for you?

**Comment by msfeldstein** [comment]
Ah ok that works, i thought `npm build` was one of those special ones i
didn't have to type `run` with

**Pull request merged**
