### PR TITLE
add albumkings.co

### PR DESCRIPTION
**Pull request by cwal**

### CODE REVIEW

**Comment by msfeldstein** [comment]
Sweet!  I will push 4.31 shortly

**Comment by cwal** [comment]
I love the addon and I am always lost when it doesn't work on a site I use! Next I am trying to get Apple Music to work as well, but since the player is loaded through javascript it isn't finding the elements I declare to watch for play/pause state

**Comment by msfeldstein** [comment]
ooh good call!  I can looks into that as well

**Comment by cwal** [comment]
using https://itunes.apple.com/us/post/idsa.99ad7481-3242-11e5-8c89-5ea061d85a5e

I have declared "#pButton" as playStateSelector and "pause" as playStateClass but getting error message "Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': The provided selector is empty."

Any ideas?

**Comment by msfeldstein** [comment]
Can you push your code to a branch so i could take a look?  It  sounds like
you're passing an empty query selector (or an empty selector is getting
passed somehow i should say).  Do you have any empty selectors defined like
`playSelector: ""` or something?

**Comment by cwal** [comment]
oh... your right I took out my empty selectors and its working... sorry! Ill push the code soon then.

**Pull request merged**
